### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by cgmb**
This project was developed as a part of the Mozilla Science Sprint,
so the MPL seems like a good fit.

### CODE REVIEW

**Comment by cgmb** [comment]
@padawin @ChrissiQ @BillMills @JeremyAdamHart @arowens @jvamosi 

We should have a license as per #90. Would everyone be ok with using MPL?

**Comment by jvamosi** [comment]
works for me!

On Jun 6, 2015, at 3:34 PM, Cory Bloor <notifications@github.com> wrote:

> @padawin @ChrissiQ @BillMills @JeremyAdamHart @arowens @jvamosi
> 
> We should have a license as per #90. Would everyone be ok with using MPL?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----------------
Jana C. Vamosi, Associate Professor
Department of Biological Sciences, University of Calgary
http://people.ucalgary.ca/~jvamosi/

**Comment by padawin** [comment]
Works for me too

**Comment by cgmb** [comment]
kk. IIRC, the Calgary group was ok with it, too. I just kinda like to have everyone chime in to that stuff in writing. But, I'll merge anyways.

**Pull request merged**
