### PR TITLE
Added css reset

### PR DESCRIPTION
**Pull request by jacobtomlinson**
To ensure consistency across browsers.

### CODE REVIEW

**Comment by cgmb** [comment]
Looks good to me.

**Comment by ChrissiQ** [comment]
It actually doesn't make sense to apply this after bootstrap.  Bootstrap uses normalize.css.  If we were not using bootstrap, this would make sense.  We will need to revert this.

**Comment by jacobtomlinson** [comment]
I hadn't realised we were using bootstrap? I thought the idea was to use as little frameworks as possible, in a similar way to BrowserQuest.

**Comment by ChrissiQ** [comment]
We added it back in the "prettify" step.  I'm not aware of any decision made to not use frameworks.  The idea was discussed in #48.

**Comment by jacobtomlinson** [comment]
Fair enough. In #32 I discussed with @padawin (via IRC and paraphrased in the issue) about keeping things simple and not using frameworks where we can help it.

**Comment by ChrissiQ** [comment]
Sorry for the confusion.  At the time I made the comment on #32, I had considered it low priority and thus suggested not using it.  However, many people wanted some minor prettifying, so we added bootstrap at the time of #48.  You can see it in index.html.

**Comment by jacobtomlinson** [comment]
Yes I see now. Sadly I think the time differences were against us yesterday and so there has been confusion on our part about what has happened.

**Comment by jacobtomlinson** [comment]
I had also added the css reset at the time of #32 and then went to sleep. I opened the PR when I woke up having not caught up with what had happened in between.

**Comment by ChrissiQ** [comment]
That makes sense.  I am not particular on using bootstrap (it's not my preference), so I think we just started to use it since it's low barrier to entry (people are used to it, and it makes it easy to 'prettify').  Most projects come to a stage where they strip it out because it's too limiting and makes things messy eventually.  If we are at that stage, we could do so!  I'm not sure if we are, though.  The easiest thing for right now might be to revert this.  If nobody wants to, I will do it in a few hours once I've really woken up ;)

**Comment by jacobtomlinson** [comment]
Yeah feel free to revert it and stick with bootstrap for now.

**Comment by cgmb** [comment]
Whoops. Well, this is why I invited  @ChrissiQ to the project. I'm OK with reverting.

**Pull request merged**
